# https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
globalArguments:
  - "--global.sendanonymoususage=false"
  - "--global.checknewversion=false"

additionalArguments:
  - "--serversTransport.insecureSkipVerify=true"
  - "--log.level=INFO"

deployment:
  enabled: true
  replicas: 1
  annotations: { }
  podAnnotations: { }
  additionalContainers: [ ]
  initContainers: [ ]

ports:
  web:
    redirectTo: websecure
  websecure:
    tls:
      enabled: true

# Create an IngressRoute for the dashboard
ingressRoute:
  dashboard:
    enabled: false

providers:
  kubernetesCRD:
    enabled: true
    ingressClass: traefik-external
    allowExternalNameServices: true
  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true
    publishedService:
      enabled: false

rbac:
  enabled: true

service:
  enabled: true
  type: LoadBalancer
  annotations: { }
  labels: { }
  #spec:
    # this should be an IP in the MetalLB range
    #loadBalancerIP: 172.16.100.11
    #loadBalancerIP: 172.30.0.21
  loadBalancerSourceRanges: [ ]
  externalIPs: [ ]
