---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${BASE_DOMAIN_DASH}-staging
  namespace: traefik
spec:
  secretName: ${BASE_DOMAIN_DASH}-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "${BASE_DOMAIN}"
  dnsNames:
  - "${BASE_DOMAIN}"

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-${BASE_DOMAIN_DASH}-staging
  namespace: traefik
spec:
  secretName: traefik-${BASE_DOMAIN_DASH}-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "traefik.${BASE_DOMAIN}"
  dnsNames:
    - "traefik.${BASE_DOMAIN}"

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k3s-${BASE_DOMAIN_DASH}-staging
  namespace: kubernetes-dashboard
spec:
  secretName: k3s-${BASE_DOMAIN_DASH}-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "k3s.${BASE_DOMAIN}"
  dnsNames:
    - "k3s.${BASE_DOMAIN}"
